version: '3.8'

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./packages/backend:/app/packages/backend
      - ./packages/shared:/app/packages/shared
      - /app/node_modules
      - /app/packages/backend/node_modules
      - /app/packages/shared/node_modules
    command: npm run dev --workspace=@workforce-navigator/backend
    networks:
      - workforce-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: workforce_navigator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - workforce-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - workforce-network

networks:
  workforce-network:
    driver: bridge

volumes:
  postgres_data: